# Generated by Django 3.1.2 on 2020-10-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Dob', models.DateField()),
                ('About', models.TextField(max_length=2000)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Celebrity')),
                ('Nationality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Celebrities.celebrity')),
            ],
        ),
    ]
