# Generated by Django 3.1.2 on 2020-10-25 08:47

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Celebrities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Statement', models.CharField(max_length=5000)),
                ('PostDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('ReleaseDate', models.DateField()),
                ('Duration', models.TimeField()),
                ('Description', models.TextField(max_length=2000)),
                ('Image', models.ImageField(default='movie.jpg', upload_to='Show')),
                ('Country', models.CharField(max_length=200)),
                ('Budget', models.IntegerField()),
                ('Boc', models.IntegerField()),
                ('Status', models.CharField(default='R', max_length=1)),
                ('Avg_rating', models.FloatField()),
                ('Num_rating', models.IntegerField(default=0)),
                ('Trailer', models.CharField(max_length=200)),
                ('Type', models.CharField(choices=[('T', 'TvSeries'), ('M', 'Movies')], max_length=1)),
                ('tagline', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('Show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.show')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.review')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShowCelebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'actor'), ('D', 'director'), ('P', 'producer'), ('W', 'writer')], max_length=1)),
                ('Celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Celebrities.celebrity')),
                ('Show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.show')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('ReleaseDate', models.DurationField()),
                ('Show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.show')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='Show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.show'),
        ),
        migrations.AddField(
            model_name='review',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('Show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.show')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(choices=[('R', 'Romance'), ('C', 'Comedy'), ('T', 'Thriller'), ('S', 'Sci-Fi'), ('D', 'Drama'), ('A', 'Action')], max_length=1)),
                ('Show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.show')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('F', 'Favourites'), ('W', 'Watchlist')], max_length=1)),
                ('Show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.show')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Duration', models.DateField()),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.season')),
            ],
        ),
    ]
